### PR TITLE
Config options cut off & not reachable

### PR DESCRIPTION
**Pull request by bklang**
Changed outer container for settings activity to ScrollView so bottom items can be viewed. Applied source formatting.

device-2015-08-31-200303

### CODE REVIEW

**Comment by Wisheri** [comment]
Great that this fixes the layout problem for 7" tablets!

However now it's a bit broken for 10" tablets. Here is the layout before the update:

screenshot_2015-09-04-17-10-35

And after:

screenshot_2015-09-04-17-11-33

The visible rooms especially is a bit annoying because now it only shows one room at a time, and scrolling it is a bit painful. So, this problem still requires a few fixes.

Do you guys wish to continue with this or shall I merge it and continue myself?

It would be great if you could also clean up the commits a bit. If I merge this the way it's right now, the history will look a bit confusing.

And really thanks for helping us with the project!

**Comment by bklang** [comment]
Hi @Wisheri,

Thanks for your feedback, and especially for testing.  I wish I could offer to help on the 10" tablets, but unfortunately I do not have one.  To make it worse, the Android emulator won't sync up to Google Calendar for some reason, even though I have an account and it works fine on the actual hardware.  If you can help me get this app working in an emulator, I could help test and ensure compatibility. Without that, I'll need to lean on your assistance.

**Comment by bklang** [comment]
Oh, and yes, I will take responsibility for cleaning up the commits. Sorry I neglected to do so before opening this PR.

**Comment by bklang** [comment]
Rebased to clean up commit history.

**Comment by Wisheri** [comment]
Great! I will now merge this and modify the layout myself so that it works good with 10" tablets also. Using the emulator is a pain in the ass with this application, so I think it's easier if I'll just do it.

**Comment by bklang** [comment]
Before you spend a bunch of time fixing layout, I should mention that I have a few more PRs coming. You can see them as branches at my fork. They mostly have to do with making buttons large enough to tap on 7" screens. If there are things I can do to make sure I don't break 10" in the process, advice would be welcome.

**Comment by Wisheri** [comment]
Ok, great! I'll try to also monitor your progress :)

If the layouts stay as a RelativeLayout you won't probably break anything. If you need to change them, don't worry just keep them coming. I'll check every pull request you'll make so that we can make it work for both sizes.

**Pull request merged**
