### PR TITLE
Using non-resource calendars

### LINKED ISSUE #31: Using regular Google calendars
Reference #25 

Using regular Google calendars in addition to resource calendars would open this application for more users. Then it wouldn't be required to have Google apps for business or Google apps for education anymore for this application to work.

### PR DESCRIPTION
**Pull request by Sebastian-Hojas**
Instead of forcing the use of resource calendars, this version allows the user to decide whether only resource calendar should be considered. This also changes:

- User goes through a setup wizard to select Google account, visible rooms and default room on first start up. Users upgrading will be forced to go through the setup.
- Non-resource calendars can be shown if selected.
- Rewrite of settings management in centralised `PreferenceManager`

This fixes #31 & #25

### CODE REVIEW

**Comment by nsobadjiev** [comment]
Hi @Sebastian-Hojas !

We have the same situation in our organisation and I'd very much like to use this feature. The question is why isn't it merged yet? Is it work in progress or something?

**Comment by Sebastian-Hojas** [comment]
@nsobadjiev This should be a working prototype - feel free to use it for your organisation, and don't forget to give us feedback on your experience!
The most honest and embarrassing answer why we haven't made progress on the PR is most likely time. ping @Wisheri

**Comment by nsobadjiev** [comment]
In the meantime, we upgraded our Google Apps account so now we are using the Google Play version. However, I also tried to run this pull request on our tablet, but it crashed on startup. The exception was:

```
D/ProgressBar: setMax, old = 100, new = 100, backtrace = android.widget.ProgressBar.<init>:302 android.widget.ProgressBar.<init>:264 android.widget.ProgressBar.<init>:260 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{f501253 V.ED.... ........ 0,0-0,0 #7f0b00b3 app:id/wizard_rooms_progressbar}
D/ProgressBar: setProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.setProgress:1337 android.widget.ProgressBar.<init>:304 android.widget.ProgressBar.<init>:264 android.widget.ProgressBar.<init>:260 java.lang.reflect.Constructor.newInstance:-2 , this = android.widget.ProgressBar{f501253 V.ED.... ........ 0,0-0,0 #7f0b00b3 app:id/wizard_rooms_progressbar}
D/ProgressBar: setSecondaryProgress, old = 0, new = 0, max = 100, backtrace = android.widget.ProgressBar.<init>:306 android.widget.ProgressBar.<init>:264 android.widget.ProgressBar.<init>:260 java.lang.reflect.Constructor.newInstance:-2 java.lang.reflect.Constructor.newInstance:288 , this = android.widget.ProgressBar{f501253 V.ED.... ........ 0,0-0,0 #7f0b00b3 app:id/wizard_rooms_progressbar}
D/ActivityThread: hoder:android.app.IActivityManager$ContentProviderHolder@5d22abb,provider,holder.Provider:android.content.ContentProviderProxy@b235bd8
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.futurice.android.reservator, PID: 7394
                  java.lang.NullPointerException: target == null
                      at java.text.RuleBasedCollator.compare(RuleBasedCollator.java:191)
                      at java.text.Collator.compare(Collator.java:194)
                      at java.util.TimSort.countRunAndMakeAscending(TimSort.java:320)
                      at java.util.TimSort.sort(TimSort.java:185)
                      at java.util.TimSort.sort(TimSort.java:169)
                      at java.util.Arrays.sort(Arrays.java:2010)
                      at java.util.Collections.sort(Collections.java:1883)
                      at com.futurice.android.reservator.model.DataProxy.getRoomNames(DataProxy.java:77)
                      at com.futurice.android.reservator.view.wizard.WizardRoomSelectionFragment.loadRooms(WizardRoomSelectionFragment.java:108)
                      at com.futurice.android.reservator.view.wizard.WizardRoomSelectionFragment$1.onCheckedChanged(WizardRoomSelectionFragment.java:77)
                      at android.widget.CompoundButton.setChecked(CompoundButton.java:152)
                      at com.futurice.android.reservator.view.wizard.WizardRoomSelectionFragment.onCreateView(WizardRoomSelectionFragment.java:80)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1638)
                      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
                      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1240)
                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1088)
                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                      at android.view.View.measure(View.java:17769)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
                      at android.view.View.measure(View.java:17769)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                      at android.view.View.measure(View.java:17769)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
                      at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:389)
                      at android.view.View.measure(View.java:17769)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
                      at android.view.View.measure(View.java:17769)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                      at android.view.View.measure(View.java:17769)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2646)
                      at android.view.View.measure(View.java:17769)
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2354)
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1378)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1602)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6443)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                      at android.view.Choreographer.doFrame(Choreographer.java:572)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                      at android.os.Handler.handleCallback(Handler.java:815)
                  	at and
```

I'm not an Android developer so I don't really know what happened and I didn't investigate much because we upgraded the account either way. If you need more information, don't hesitate to ask me. We were using a cheap Lenovo TAB3 with Android 5.0.

**Comment by Wisheri** [comment]
Hi @nsobadjiev 

We finally have some time to develop this project forward. This pull request is high on the priority list and we will get back to you with any updates that we have.

Thanks for reporting that error. We will have a look at it!

**Comment by Sebastian-Hojas** [comment]
@ninjahoahong Agreed, we could definitely handle this better. I am also super happy to see this moving forward!
I don't think I'll be able to make the requested changes in the upcoming weeks, so I'd be happy if someone can take it from here.

**Comment by ninjahoahong** [comment]
Hi @nsobadjiev, I couldn't reproduce the problem. Would you mind to check the PR again and see if you still get the error, please? Thank you so much.

**Comment by nsobadjiev** [comment]
@ninjahoahong Unfortunately, we upgraded our Google Apps account and the app works as expected. I can try to build from source again, but I think it will work fine. Do you have test accounts I can use?

**Comment by ninjahoahong** [comment]
@nsobadjiev if it is working for your Google Apps account, it is okay. Unfortunately, I don't have a test accounts. When we have new release, if the problem raised again then we can look at it much better.

**Pull request merged**
